let hours = [
  {
    Venue: "Zoo",
    Date_Start: "March 1",
    Date_End: "October 31",
    Monday_Start: "9:30 AM",
    Monday_End: "4:00 PM",
    Tuesday_Start: "9:30 AM",
    Tuesday_End: "4:00 PM",
    Wednesday_Start: "9:30 AM",
    Wednesday_End: "4:00 PM",
    Thursday_Start: "9:30 AM",
    Thursday_End: "4:00 PM",
    Friday_Start: "9:30 AM",
    Friday_End: "4:00 PM",
    Saturday_Start: "9:30 AM",
    Saturday_End: "5:00 PM",
    Sunday_Start: "9:30 AM",
    Sunday_End: "5:00 PM",
  },
  {
    Venue: "Zoo",
    Date_Start: "November 1",
    Date_End: "February 28",
    Monday_Start: "9:30 AM",
    Monday_End: "4:00 PM",
    Tuesday_Start: "9:30 AM",
    Tuesday_End: "4:00 PM",
    Wednesday_Start: "9:30 AM",
    Wednesday_End: "4:00 PM",
    Thursday_Start: "9:30 AM",
    Thursday_End: "4:00 PM",
    Friday_Start: "9:30 AM",
    Friday_End: "4:00 PM",
    Saturday_Start: "9:30 AM",
    Saturday_End: "4:00 PM",
    Sunday_Start: "9:30 AM",
    Sunday_End: "4:00 PM",
  },
  {
    Venue: "JoCo Library",
    Date_Start: "January 1",
    Date_End: "December 31",
    Monday_Start: "9:00 AM",
    Monday_End: "8:00 PM",
    Tuesday_Start: "9:00 AM",
    Tuesday_End: "8:00 PM",
    Wednesday_Start: "9:00 AM",
    Wednesday_End: "8:00 PM",
    Thursday_Start: "9:00 AM",
    Thursday_End: "8:00 PM",
    Friday_Start: "9:00 AM",
    Friday_End: "6:00 PM",
    Saturday_Start: "9:00 AM",
    Saturday_End: "5:00 PM",
    Sunday_Start: "Closed",
    Sunday_End: "Closed",
  },
  {
    Venue: "Science City",
    Date_Start: "Memorial Day",
    Date_End: "Labor Day",
    Monday_Start: "10:00 AM",
    Monday_End: "5:00 PM",
    Tuesday_Start: "10:00 AM",
    Tuesday_End: "5:00 PM",
    Wednesday_Start: "10:00 AM",
    Wednesday_End: "5:00 PM",
    Thursday_Start: "10:00 AM",
    Thursday_End: "5:00 PM",
    Friday_Start: "10:00 AM",
    Friday_End: "5:00 PM",
    Saturday_Start: "10:00 AM",
    Saturday_End: "5:00 PM",
    Sunday_Start: "12:00 PM",
    Sunday_End: "5:00 PM",
  },
  {
    Venue: "Science City",
    Date_Start: "Labor Day",
    Date_End: "Memorial Day",
    Monday_Start: "Closed",
    Monday_End: "Closed",
    Tuesday_Start: "10:00 AM",
    Tuesday_End: "5:00 PM",
    Wednesday_Start: "10:00 AM",
    Wednesday_End: "5:00 PM",
    Thursday_Start: "10:00 AM",
    Thursday_End: "5:00 PM",
    Friday_Start: "10:00 AM",
    Friday_End: "5:00 PM",
    Saturday_Start: "10:00 AM",
    Saturday_End: "5:00 PM",
    Sunday_Start: "12:00 PM",
    Sunday_End: "5:00 PM",
  },
  {
    Venue: "Wonderscope",
    Date_Start: "January 1",
    Date_End: "December 31",
    Monday_Start: "Closed",
    Monday_End: "Closed",
    Tuesday_Start: "9:00 AM",
    Tuesday_End: "4:30 PM",
    Wednesday_Start: "9:00 AM",
    Wednesday_End: "4:30 PM",
    Thursday_Start: "9:00 AM",
    Thursday_End: "4:30 PM",
    Friday_Start: "9:00 AM",
    Friday_End: "4:30 PM",
    Saturday_Start: "9:00 AM",
    Saturday_End: "5:00 PM",
    Sunday_Start: "12:00 PM",
    Sunday_End: "5:00 PM",
  },
  {
    Venue: "Deanna Rose Farmstead",
    Date_Start: "April 1",
    Date_End: "October 31",
    Monday_Start: "9:00 AM",
    Monday_End: "5:00 PM",
    Tuesday_Start: "9:00 AM",
    Tuesday_End: "5:00 PM",
    Wednesday_Start: "9:00 AM",
    Wednesday_End: "5:00 PM",
    Thursday_Start: "9:00 AM",
    Thursday_End: "5:00 PM",
    Friday_Start: "9:00 AM",
    Friday_End: "5:00 PM",
    Saturday_Start: "9:00 AM",
    Saturday_End: "5:00 PM",
    Sunday_Start: "9:00 AM",
    Sunday_End: "5:00 PM",
  },
  {
    Venue: "Leawood Aquatic Center",
    Date_Start: "Memorial Day",
    Date_End: "August 14",
    Monday_Start: "11:30 AM",
    Monday_End: "8:00 PM",
    Tuesday_Start: "11:30 AM",
    Tuesday_End: "8:00 PM",
    Wednesday_Start: "11:30 AM",
    Wednesday_End: "8:00 PM",
    Thursday_Start: "11:30 AM",
    Thursday_End: "8:00 PM",
    Friday_Start: "11:30 AM",
    Friday_End: "8:00 PM",
    Saturday_Start: "11:30 AM",
    Saturday_End: "8:00 PM",
    Sunday_Start: "11:30 AM",
    Sunday_End: "8:00 PM",
  },
  {
    Venue: "Leawood Aquatic Center",
    Date_Start: "August 15",
    Date_End: "Labor Day",
    Monday_Start: "Closed",
    Monday_End: "Closed",
    Tuesday_Start: "4:00 PM",
    Tuesday_End: "7:00 PM",
    Wednesday_Start: "Closed",
    Wednesday_End: "Closed",
    Thursday_Start: "4:00 PM",
    Thursday_End: "7:00 PM",
    Friday_Start: "Closed",
    Friday_End: "Closed",
    Saturday_Start: "11:30 AM",
    Saturday_End: "6:00 PM",
    Sunday_Start: "11:30 AM",
    Sunday_End: "6:00 PM",
  },
  {
    Venue: "Overland Park Arboretum",
    Date_Start: "September 1",
    Date_End: "March 30",
    Monday_Start: "9:00 AM",
    Monday_End: "5:00 PM",
    Tuesday_Start: "9:00 AM",
    Tuesday_End: "5:00 PM",
    Wednesday_Start: "9:00 AM",
    Wednesday_End: "5:00 PM",
    Thursday_Start: "9:00 AM",
    Thursday_End: "5:00 PM",
    Friday_Start: "9:00 AM",
    Friday_End: "5:00 PM",
    Saturday_Start: "9:00 AM",
    Saturday_End: "5:00 PM",
    Sunday_Start: "9:00 AM",
    Sunday_End: "5:00 PM",
  },
  {
    Venue: "Overland Park Arboretum",
    Date_Start: "April 1",
    Date_End: "August 30",
    Monday_Start: "9:00 AM",
    Monday_End: "5:00 PM",
    Tuesday_Start: "9:00 AM",
    Tuesday_End: "8:00 PM",
    Wednesday_Start: "9:00 AM",
    Wednesday_End: "5:00 PM",
    Thursday_Start: "9:00 AM",
    Thursday_End: "8:00 PM",
    Friday_Start: "9:00 AM",
    Friday_End: "5:00 PM",
    Saturday_Start: "9:00 AM",
    Saturday_End: "5:00 PM",
    Sunday_Start: "9:00 AM",
    Sunday_End: "5:00 PM",
  },
  {
    Venue: "Prarie Fire Museum",
    Date_Start: "January 1",
    Date_End: "December 31",
    Monday_Start: "10:00 AM",
    Monday_End: "5:00 PM",
    Tuesday_Start: "10:00 AM",
    Tuesday_End: "5:00 PM",
    Wednesday_Start: "10:00 AM",
    Wednesday_End: "5:00 PM",
    Thursday_Start: "10:00 AM",
    Thursday_End: "5:00 PM",
    Friday_Start: "10:00 AM",
    Friday_End: "5:00 PM",
    Saturday_Start: "10:00 AM",
    Saturday_End: "5:00 PM",
    Sunday_Start: "12:00 PM",
    Sunday_End: "5:00 PM",
  },
];

hours.sort((a, b) => a.Venue > b.Venue);

export default hours;
